language: python

python:
  - "3.5"
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt

script:
     - pytest --cov=app --cov-report term-missing tests/ -s -r a --color=yes -vvv
     - coveralls
