.SILENT:

stop:
	docker-compose stop

up:stop
	docker-compose up

build:stop
	docker-compose build

test:stop
	docker-compose run --rm small pytest --cov=app --cov-report term-missing tests/${path} -s -r a --color=yes -vvv


shell:stop
	docker-compose run --rm small flask shell

install:stop
	docker-compose build
	rm -rf .tmp/*
	docker-compose stop
	docker-compose run --rm small flask db upgrade
	docker-compose stop

init:stop
	docker-compose run --rm small flask db init

makemigrations:stop
	docker-compose run --rm small flask db migrate

migrate:stop
	docker-compose run --rm small flask db upgrade

makemigrations_empty:
	docker-compose run --rm small flask db revision

access:
	docker exec -it small-gateway sh

drop_datebase:
	rm -rf .tmp/*
