.SILENT:

up:
	docker-compose stop
	docker-compose up

build:
	docker-compose stop
	docker-compose build

test:
	docker-compose stop
	docker-compose run --rm small pytest --cov=app --cov-report term-missing tests/${path} -s -r a --color=yes -vvv


shell:
	docker-compose stop
	docker-compose run --rm small flask shell
