"""empty message

Revision ID: 5520d8660008
Revises: 992740437761
Create Date: 2018-08-05 20:28:14.409423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5520d8660008'
down_revision = '992740437761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'status')
    # ### end Alembic commands ###
