"""empty message

Revision ID: 992740437761
Revises:
Create Date: 2018-08-05 14:51:52.201065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992740437761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buyer',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('cpf', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'card',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('holder_name', sa.String(length=100), nullable=False),
        sa.Column('number', sa.String(length=50), nullable=False),
        sa.Column('expiration_date', sa.String(length=10), nullable=False),
        sa.Column('cvv', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    client_table = op.create_table(
        'client',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    type_table = op.create_table(
        'type',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'payment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('card_id', sa.Integer(), nullable=True),
        sa.Column('type_id', sa.Integer(), nullable=False),
        sa.Column('buyer_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('update_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
        sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
        sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # http://alembic.zzzcomputing.com/en/latest/ops.html?highlight=insert#alembic.operations.Operations.bulk_insert
    op.bulk_insert(client_table, [{
        "id": 1,
        "name": "Moip Client"
    }])

    op.bulk_insert(type_table, [
            {"id": 1, "name": "Credit card"},
            {"id": 2, "name": "Boleto"}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('type')
    op.drop_table('client')
    op.drop_table('card')
    op.drop_table('buyer')
    # ### end Alembic commands ###
