"""empty message

Revision ID: f5e00a3aa97c
Revises: 5520d8660008
Create Date: 2018-08-07 03:11:41.457219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e00a3aa97c'
down_revision = '5520d8660008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('brand', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'brand')
    # ### end Alembic commands ###
